[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
horse_racing = "3rM2gVWd4WbK9m8Vyy4SYMKLvxfFbcaU2yCUNfNCwY2r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
